package com.umati.springboot.model;



import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;


@Entity
@Table(name = "users",schema = "demo")
@ApiModel(description = "All details about the User")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "User id generated by the Database")
    private long id;
    @ApiModelProperty(notes = "Username for the user ")
    private String username;
    @ApiModelProperty(notes = "User full name for the User ")
    private String fullName;
    @ApiModelProperty(notes = "User address for the User")
    private String address;
    @ApiModelProperty(notes = "User mobile number for the User")
    private long mobile;

    public User()
    {

    }

    @Override
    public boolean equals(Object o) {
        return super.equals(o);
    }

    public User( String username, String fullName, String address, long mobile) {
        this.username = username;
        this.fullName = fullName;
        this.address = address;
        this.mobile = mobile;
    }


    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public long getMobile() {
        return mobile;
    }

    public void setMobile(long mobile) {
        this.mobile = mobile;
    }

    @Override
    public String toString() {
        return super.toString();
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
