package com.umati.springboot.model;



import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;


@Entity
@Table(name = "users",schema = "demo")
@ApiModel(description = "All details about the User")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "User id generated by the Database")
    private long id;
    @ApiModelProperty(notes = "Username for the user ")
    private String username;
    @ApiModelProperty(notes = "User full name for the User ")
    private String fullname;
    @ApiModelProperty(notes = "User address for the User")
    private String address;
    @ApiModelProperty(notes = "User mobile number for the User")
    private long mobile;
    @ApiModelProperty(notes = "User password for the User")
    private String password;
    @ApiModelProperty(notes = "User status for the User")
    private boolean isActivated;


    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    public User()
    {

    }

    @Override
    public boolean equals(Object o) {
        return super.equals(o);
    }

    public User(String userName, String fullname, String address, long mobile, String password, boolean isActivated) {
        this.username = userName;
        this.fullname = fullname;
        this.address = address;
        this.mobile = mobile;
        this.password=password;
        this.isActivated = isActivated;
    }


    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getfullname() {
        return fullname;
    }

    public void setfullname(String fullname) {
        this.fullname = fullname;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public long getMobile() {
        return mobile;
    }

    public void setMobile(long mobile) {
        this.mobile = mobile;
    }

    @Override
    public String toString() {
        return super.toString();
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public boolean isActivated() {
        return isActivated;
    }

    public void setActivated(boolean activated) {
        isActivated = activated;
    }
}
